#
# Helm chart to install the Spring Cloud Config server
# Commands to be executed
# kubectl create ns config-storage
# helm repo add kiwigrid https://kiwigrid.github.io
# helm install \
#    spring-cloud-config-server kiwigrid/spring-cloud-config-server \
#    -n config-storage \
#    -f src/main/configs/helm.yml
#
# helm delete spring-cloud-config-server -n config-storage
#
config:
  gitUri: https://github.com/quarkus-for-spring-developers/sccs-config-repo
  gitSearchpath: {application}
extraEnv:
  - name: SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT-LABEL
    value: main
